"""empty message

Revision ID: 30f983843650
Revises: 2caab9bbed74
Create Date: 2021-11-15 17:36:08.290601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f983843650'
down_revision = '2caab9bbed74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'plants', 'employees', ['director_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plants', type_='foreignkey')
    # ### end Alembic commands ###
