# Generated by Django 3.1.7 on 2021-12-02 18:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_column'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('name', 'owner')},
        ),
    ]
