# Generated by Django 3.1.7 on 2021-12-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20211202_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
