# Generated by Django 3.1.7 on 2021-12-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_board_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
